pipeline {
    agent any
    tools{
        gradle 'gradle'
    }
    environment{
        dockerImage = ''
    }

    stages {
        stage('secret.yml download'){
            steps{
                withCredentials([file(credentialsId: 'application-secret', variable: 'configFile')]){
                    script{
                        sh "cp $configFile Back/src/main/resources/application-prod-secret.yml"
                    }
                }
                // withCredentials([file(credentialsId: 'key-store', variable: 'keyFile')]){
                //     script{
                //         sh "cp $keyFile Back/keystore.p12"
                //     }
                // }
            }
        }
        stage('Build'){
            steps{
                dir("./Back"){
                    sh "chmod +x gradlew"
                    sh "gradle wrapper"
                    sh "./gradlew clean build"
                }
            }
        }
        stage("Build Image"){
            steps{
                dir("./Back"){
                    script{
                        dockerImage = docker.build("runMate"+":$BUILD_NUMBER")
                      }
                }
            }
        }
//         stage('Push image') {
//             steps{
//                 script{
//                     docker.withRegistry('https://registry.hub.docker.com', 'dockerhub'){
//                         dockerImage.push("${env.BUILD_NUMBER}")
//                         dockerImage.push("latest")
//                     }
//                 }
//             }
//         }
         stage('stop prev container'){
            steps {
                script {
                    try {
                        sh 'docker stop runMate'
                        sh 'docker rm runMate'
                    } catch (e) {
                        echo 'no prev container'
                    }
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    // 이미지를 기반으로 컨테이너 실행
                    dockerImage.run("-p 8000:8000 --name runMate -d")
                }
            }
        }
        stage('Cleaning up'){
            steps{
                sh "docker rmi runMate:$BUILD_NUMBER"
            }
        }
    }
}
